### ISSUE TITLE
whatthelock shows a couple of errors.

### ISSUE THREAD

**Issue by Dhyfer1** [bmmlms/whatthelock#1]
Hi @bmmlms 

I have tested both versions of whatthelock (0.1.0 and 0.1.1) and both show these two errors:

1. Error loading translations > This error appears when installing/uninstalling whatthelock 
![image_3](https://github.com/bmmlms/whatthelock/assets/50301201/dad08482-5ae1-4beb-ab8a-e3fdb61abbbc)
2. Acces violation > This error appears when I click on the Check with What The Lock... item in the file explorer context menu for any file/folder that I select.
![image](https://github.com/bmmlms/whatthelock/assets/50301201/4195d07e-42b8-4b47-b5a6-dc143fd56850)

Both bugs happen in Windows 11 Pro 64bits - Insider Beta Channel

**Comment by bmmlms** [comment]
Please try again with the latest version, it should be fixed.

**Comment by Dhyfer1** [comment]
> Please try again with the latest version, it should be fixed.

Hey, thanks a lot for fixing the bugs. whatthelock works as expected. 😊
